heat_template_version: 2021-04-16
description: "creating VM"
resources: 
  my_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules: 
        - ethertype: IPv4
          protocol: tcp
          remote_mode: remote_ip_prefix
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: "0.0.0.0/0"
        - ethertype: IPv4
          protocol: tcp
          remote_mode: remote_ip_prefix
          port_range_min: 8080
          port_range_max: 8080
          remote_ip_prefix: "0.0.0.0/0"
      description: "My security group for app instance"
      
  my_server: 
    type: "OS::Nova::Server"
    properties: 
      name: "turbina-docker"
      flavor: "m1.small"
      image: "d608627a-ef62-452d-8a74-1c307cbe276d"
      availability_zone: nova
      key_name: "2025-turbina"
      networks:
      - port: { get_resource: my_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            sudo apt-get update -y
            sudo apt-get install -y mariadb-server openjdk-21-jdk
            sudo systemctl start mariadb
            echo "Setting up MariaDB with root password 'toor'"
            echo -e "\n\n\ntoor\ntoor\ny\ny\ny\ny" | sudo mysql_secure_installation
            sudo systemctl restart mariadb
            sudo mysql -u root -ptoor -e "CREATE DATABASE quizbot;"
          params: {}
    depends_on: 
      - my_security_group

  my_port:
    type: OS::Neutron::Port
    properties:
      network_id: "17eae9b6-2168-4a07-a0d3-66d5ad2a9f0e" # students.net ID
      security_groups:
        - default
        - { get_resource: my_security_group }
